General Improvements
1. Removed linking msvcrt to avoid some warnings when compiling with MSVC...
2. Fixed bindings for Nelua and LuaJIT and DragonRuby, Plus that examples where added for them...
3. Fixed ice_al.h on Microsoft platforms
4. Fixed undefined reference to ice_batt_get_info in ice_batt.h and now removed "using namespace" lines for C++ implementations (UWP, BlackBerry 10) and added correct headers...
5. In ice_clip.h, removed "using namespace" lines for C++ implementations (UWP, BlackBerry 10) and added correct headers, In addition to check if no data is in Clipboard on Windows (Example now does not error and terminate if the Clipboard has no text...)
6. Fixed ice_cpu.h implementation for Microsoft platforms and removed requirement for C string functions...
7. Typo fixes (Retrive -> Retrieve)
8. Updated usage examples inside the headers...
9. In ice_str.h now ice_str_len returns NULL (zero) safely as string length if NULL (or zero) passed as parameter...
10. Updated header implementations and samples to comply with -Wextra flag!
11. ice_test.h now asserts for being the strings are not NULL (or zero) when comparing using ICE_TEST_ASSERT_STR_EQU and also used ICE_TEST_CREATE instead of ICE_TEST_CREATE_EX in the usage example...
12. Added disable security pragmas for ice_time.h so it won't warn because we are not using the C11 secure versions of the standard C library functions...
13. The examples of the bindings with the samples by all were both tested with MSVC and GCC on Microsoft Windows and they should also work fine on any other C compiler or platform as it can use the suitable implementation...